version: '3.4'
services:
  web:
    build:
      context: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    ports:
      - 7337:7337

  backend:
    build:
      context: .
      dockerfile: Dockerfile.deploy
    restart: unless-stopped
    ports:
      - 3000:3000
