kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
data:
{{- range $key, $val := .Values.configmap }}
  {{ $key }} : {{ $val | quote }}
{{- end }}
